EXP_NAME: gta2cityscapes_mapillary_mtkt_pretrained
SOURCE: GTA
TARGETS:
    - Cityscapes
    - Mapillary
NUM_WORKERS: 4
TEST:
  MODE: single
  MODEL:
    - DeepLabv2MTKT
  RESTORE_FROM:
    - ../../pretrained_models/gta2cityscapes_mapillary_mtkt.pth
